language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text
